version: 2.1

jobs:
  cypress-e2e-tests:
    docker:
      # Используем официальный, стабильный образ CircleCI с предустановленными браузерами (Chrome, Firefox)
      - image: cimg/node:20.11.0-browsers

    steps:
      # Скачиваем код из репозитория GitHub
      - checkout

      # Устанавливаем зависимости проекта (Cypress и сопутствующие npm-пакеты)
      - run:
          name: Install npm packages
          command: npm ci

      # Запускаем e2e тесты Cypress в режиме headless
      - run:
          name: Run Cypress tests
          command: npx cypress run

      # Сохраняем сгенерированный HTML-отчет в артефакты CircleCI
      - store_artifacts:
          path: cypress/reports/html
          destination: Cypress-HTML-Report

workflows:
  build-and-test:
    jobs:
      - cypress-e2e-tests
